### ISSUE TITLE
static IP for endpoint/service residing in AKS 

### ISSUE THREAD

**Issue by michaelatln** [open-tsm/inssre-azure-issues#1]
Use case to have static ip for your endpoint/service residing on AKS ingress/LB behind Frontdoor  and provide to customer for whitelisting , its for the same application we discussed eventhub as well (Rules).

**Comment by nikuljain** [comment]
option 1 : Traffic manager + nginx ingress 
option 2 : internal dns model we have right now 

**Issues** : if WAF is mandatory
option 1 : Traffic Manager + nginx enterprise 
opton 2 : Traffic Manager + App gateway(just for WAF) pass through + nginx ingress LB

**Comment by michaelatln** [comment]
https://docs.microsoft.com/en-us/azure/aks/static-ip#create-a-service-using-the-static-ip-address
