### ISSUE TITLE
Data replication best practices between primary and secondary

### ISSUE THREAD

**Issue by michaelatln** [open-tsm/inssre-azure-issues#2]

**Comment by michaelatln** [comment]
- one way replication vs two-way replication (restore data back to primary region)
- when both region are up, Geo redundancy allows two-way replication
- however during failover situation: it becomes local redundancy
- when the other region is backup, the geo-redundancy needs to be re-enabled and the replication start from fresh
-

**Comment by nikuljain** [comment]
https://docs.microsoft.com/en-us/azure/storage/common/storage-disaster-recovery-guidance?toc=/azure/storage/blobs/toc.json#design-for-high-availability
